### ISSUE TITLE
[Client] Hardware integration: Install touch screen

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#12]
Install [eleduino touch screen](http://www.eleduino.com/7-0-Inch-1024x600-Pixel-IPS-Hdmi-Input-Capacitive-Touch-Screen-Support-Raspberry-pi-Banana-Pi-Pro-Be-p10533.html) ... when available.

Also, this will probably be a good moment to create an independent BSP layer.

**Comment by indisoluble** [comment]
Let start by creating the BSP layer.

**Comment by indisoluble** [comment]
Done in [commit d5fa45a](https://github.com/comodoo/meta-comodoo/commit/d5fa45a82e55077d21acb3c3c68102e8b5a0b3a2).

**Comment by indisoluble** [comment]
Touch screen installed and ready: [commit d3948af](https://github.com/comodoo/meta-comodoo/commit/d3948afc3a9f7905392ab8359e11d586c6621b3a).

Let test it a bit more to see if everything is OK.

**Comment by indisoluble** [comment]
No problem so far, although sometimes the screen does not detect our touches right after switching on the RPi and we have to disconnect and connect again the screen to the USB port. Or is it OS faults? One way or the other, I would rather carry on with this Beta and come back to this once we have slimmed down our Yocto image (issue #3) ... and if the problem persists.
