### ISSUE TITLE
Create Tag for BSP based on Krogoth

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#27]

**Comment by javiroman** [comment]
the last working meta-comodoo branch, in order to freeze a well know working BSP (before working with Morty version of yocto in the main branch)

**Comment by indisoluble** [comment]
These are the tagging and branching conventions in Yocto:
- https://wiki.yoctoproject.org/wiki/Yocto_Project_Tagging_Conventions
- https://wiki.yoctoproject.org/wiki/Yocto_Project_Branch_Conventions

I think we should follow them too. In this way, if someone decides to follow our project, it will be a lot easier for him or her to know where we are and where we are heading.

**Comment by indisoluble** [comment]
Based on the comment above, I am going to:
1. Remove all branches but `master` & `krogoth-syslog`
2. Create a new release branch called `krogoth`
3. Tag the last commit in branch `krogoth` with `krogoth-1.0.0`
4. Create another release branch called `morty` and make it the default branch
