### ISSUE TITLE
As an administrator I want to slim down our image, so that we can manage a smaller size

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#3]
At this moment (commit [a438268](https://github.com/indisoluble/meta-comodoo/commit/a4382687cc934a23d65f1b17f5e6cd0c16e628ee)), our image **comodoo-image-firefox** has a size of **480 MB**. We should try to slim it down.

**Comment by javiroman** [comment]
Notice: root does not have a password, I think we should ask for one in the first startup (see US #17).

**Comment by indisoluble** [comment]
FTR, the image based on morty is 697MB.

**Comment by indisoluble** [comment]
Have a look to: [Building a Tiny System](http://www.yoctoproject.org/docs/2.2.1/mega-manual/mega-manual.html#building-a-tiny-system)

**Comment by indisoluble** [comment]
Image size reduced from 696MB to 476MB.
