### ISSUE TITLE
[Client] Do something with 'sleep' calls

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#4]
[comodoo-pos.py](https://github.com/comodoo/meta-comodoo/blob/master/meta-comodoo/recipes-core/pos-launcher/comodoo-pos-launcher/comodoo-pos.py#L85) waits for 8 seconds before checking if the Rpi is already connected to a LAN. `eca-web` also has a few `sleep` calls distributed along its code ... big code smell, I should get rid off them ... somehow.

**Comment by javiroman** [comment]
Related with https://github.com/comodoo/meta-comodoo/issues/5

**Comment by indisoluble** [comment]
Issue #23 makes this one make this not applicable.
