### ISSUE TITLE
[Misc] Have a look to addon 'Punto de venta adaptado a la legislación española

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#8]
Look like we should include this addon by default: [Punto de venta adaptado a la legislación española](https://www.odoo.com/apps/modules/8.0/l10n_es_pos/). Although it is for Odoo version 8.0, while we are using version 9.0; or, at least, that is the version of the docker I am using in my host computer.

**Comment by indisoluble** [comment]
Uhm ... this is in fact a _server related_ issue ... I am going to close it and copy it in the right project.
